### ISSUE TITLE
Remove crashing cross-built aarch64 wheel, in favor of working native builds

### ISSUE THREAD

**Issue by PhilMiller** [scikit-build/cmake-python-distributions#110]
OS: Ubuntu 18.04.4
Architecture: aarch64, on Amazon AWS c6 instance

The wheel for aarch64 on PyPI provides a non-functioning binary:

```
$ pip install cmake
Collecting cmake
  Using cached cmake-3.18.0-py3-none-manylinux2014_aarch64.whl (15.1 MB)
Installing collected packages: cmake
Successfully installed cmake-3.18.0
$ which cmake
/home/ubuntu/venv-cmake/bin/cmake
$ cmake --version
$ echo $?
245
```

This seems to be related to the discussion on [this issue](https://github.com/scikit-build/cmake-python-distributions/issues/96)

Forcing installation not to use the wheel provides a working binary:

```
$ pip install --no-binary :all: cmake
Collecting cmake
  Using cached cmake-3.18.0.tar.gz (28 kB)
Skipping wheel build for cmake, due to binaries being disabled for it.
Installing collected packages: cmake
    Running setup.py install for cmake ... done
Successfully installed cmake-3.18.0
$ which cmake
/home/ubuntu/venv-cmake/bin/cmake
$ cmake --version
cmake version 3.18.0

CMake suite maintained and supported by Kitware (kitware.com/cmake).
```

Thus, I'm asking that until the build issues are resolved, they be avoided so that users get a working result

**Comment by jcfr** [comment]
Closing. This was addressed in https://github.com/scikit-build/cmake-python-distributions/issues/96#issuecomment-663112089
