### ISSUE TITLE
macOS Python 3 wheel missing due to broken travis build!

### ISSUE THREAD

**Issue by henryiii** [scikit-build/cmake-python-distributions#112]
Can someone (@jcfr, possibly?) please restart the Travis CI build? It broke, causing macOS wheels for CMake 3.18.2 Python 3 to not upload, killing downstream projects who try to build with CMake's pip package (since it tried to build with the tarball).

In the future, I have found GitHub Actions / Azure to be much more reliable than Travis for macOS. ;)

```
[scikit-ci] Executing: python ../addons/travis/install_pyenv.py
195dyld: Library not loaded: /usr/local/opt/gettext/lib/libintl.8.dylib
196  Referenced from: /Users/travis/.pyenv/versions/3.7.4/bin/python
197  Reason: Incompatible library version: python requires version 11.0.0 or later, but libintl.8.dylib provides version 10.0.0
198/var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/tmpqIYbnV.sh: line 2:  2975 Abort trap: 6           python ../addons/travis/install_pyenv.py
199
200A command failed while executing BEFORE_INSTALL step.
201  Return code:
202    134
203  Command:
204    python ../addons/travis/install_pyenv.py
205  Working directory:
206    /Users/travis/build/scikit-build/cmake-python-distributions
207
208Please see above for more information.
209
210The command "ci install" failed and exited with 1 during .
```

CC @jpivarski, who discovered this due to AwkwardArray's CI failing.

**Comment by jcfr** [comment]
> If ignore duplicates is on for twine, you technically can just release 3.18.2 again

Great idea. I will add the flag then.

**Comment by jcfr** [comment]
Turns out we already pass that option. Since the release process is triggered when a tag is pushed, I will just push a new tag. 

Also true I could deleted the previous tag ... and push again

**Comment by jcfr** [comment]
Release 3.18.2.post1 in progress

**Comment by jcfr** [comment]
Closing. Release packages available at https://pypi.org/project/cmake/#files
