### ISSUE TITLE
[CI] build failing

### ISSUE THREAD

**Issue by mayeut** [scikit-build/cmake-python-distributions#129]
CI builds are failing on:
- ci/circleci: manylinux-x64_cp37-cp37m_upload-sdist
- ci/circleci: manylinux-x86_cp37-cp37m
- travis-ci: macOS

PR #128 should fix the issue with manylinux.
I gave up trying to fix macOS.

**Comment by jcfr** [comment]
## travis-ci: macOS

In the short term, suggested path forward is to try running `brew uninstall --cask --force java` before `brew update`

For reference here is the error:

> [travis:install_pyenv.py] Executing: brew update
> ==> Downloading https://github.com/Homebrew/homebrew-portable-ruby/releases/download/2.6.3_2/portable-ruby-2.6.3_2.yosemite.bottle.tar.gz
> ######################################################################## 100.0%
> ==> Pouring portable-ruby-2.6.3_2.yosemite.bottle.tar.gz
> ==> Homebrew is run entirely by unpaid volunteers. Please consider donating:
>   https://github.com/Homebrew/brew#donations
> Updated 2 taps (homebrew/cask and homebrew/core).
> ==> java has been moved to Homebrew.
> To uninstall the cask, run:
>   brew uninstall --cask --force java
> ==> Installing java...
> Warning: You are using macOS 10.13.
> We (and Apple) do not provide support for this old version.
> You will encounter build failures with some formulae.
> Please create pull requests instead of asking for help on Homebrew's GitHub,
> Twitter or any other official channels. You are responsible for resolving
> any issues you experience while you are running this
> old version.

Source: https://travis-ci.com/github/scikit-build/cmake-python-distributions/jobs/496798097

**Comment by jcfr** [comment]
In  the meantime, I will revert my change and integrate the PR.

**Comment by mayeut** [comment]
@jcfr, 

I went another way in #131  than trying to fix brew on macOs.
It's not clean enough to be merged as-is but it's too late for me to continue this tonight.
Feel free to experiment some clean-ups in this branch if you want to, otherwise I'll have another look at it this week.

**Comment by jcfr** [comment]
Thanks so much :pray: 

> It's not clean enough to be merged as-is but it's too late for me to continue this tonight.
> Feel free to experiment some clean-ups in this branch if you want to, otherwise I'll have another look at it this week.

I understand, and I will make sure to comment here if I make some more progress

**Comment by jcfr** [comment]
Closing. Fixed  in https://github.com/scikit-build/cmake-python-distributions/pull/128 and https://github.com/scikit-build/cmake-python-distributions/pull/131
