### ISSUE TITLE
Universal2 wheel on macOS

### ISSUE THREAD

**Issue by henryiii** [scikit-build/cmake-python-distributions#132]
We need to produce a universal wheel with CMake 3.19.2+ (probably will just work on 3.20). We still need a non-universal2 wheel too, since older pips can't download a universal2 wheel. There were also renames as part of the 3.20 release, so those will need to get updated on upgrade to 3.20, too.

**Comment by jcfr** [comment]
> There were also renames as part of the 3.20 release

Do we have references to these ?

**Comment by henryiii** [comment]
Last two bullets of https://cmake.org/cmake/help/latest/release/3.20.html#other-changes . For linux, the `L` in the filename was changed to `l`. :) Not sure how much Windows changed.

**Comment by henryiii** [comment]
And, of course, macOS had already changed to the universal2 name in 3.19.2.
