### ISSUE TITLE
Missing wheel for Linux x86

### ISSUE THREAD

**Issue by henryiii** [scikit-build/cmake-python-distributions#141]
The wheel for x86 linux is missing from 3.20.2, due to a bug in the CircleCI config.

@jcfr or @thewtex, could you add `henryiii` as a maintainer on at least the cmake package on PyPI? I need to either build a wheel manually and upload it or yank the release while we debug.

@mayeut could you check the CircleCI config? If we could get it to trigger and upload just the one missing wheel, that could also be a workaround, but I'm not as familiar with CircleCI (vs. GHA/Azure/Travis/Appveyor).

**Comment by henryiii** [comment]
`check_dist` seems not to be running on the tag, and it's required for the deploy step.

**Comment by jcfr** [comment]
> could you add henryiii as a maintainer on at least the cmake package on PyPI?

All set. Thanks for helping with this :pray: :100:

**Comment by mayeut** [comment]
@henryiii,
 
I don't know CircleCI either so just looking at the possible why from the diff with the build jobs, seems to be a missing `<<: *no_filters` on the `check_dist` job.

**Comment by henryiii** [comment]
Thanks! I should have manylinux wheels build locally via cibuildwheel in a few minutes.

```console
git checkout 3.20.2
CIBW_BUILD='cp39-*' \
  CIBW_MANYLINUX_X86_64_IMAGE=dockcross/manylinux1-x64 \
  CIBW_MANYLINUX_I686_IMAGE=dockcross/manylinux1-x86 \
  CIBW_BEFORE_BUILD="pip install -r requirements-dev.txt" \
  CIBW_REPAIR_WHEEL_COMMAND="python scripts/repair_wheel.py -w {dest_dir} {wheel}" \
  CIBW_TEST_REQUIRES="-r requirements-dev.txt" \
  CIBW_TEST_COMMAND="pytest {project}/tests" \
  CIBW_ENVIRONMENT_LINUX="SKBUILD_CONFIGURE_OPTIONS='-DOPENSSL_ROOT_DIR:PATH=/usr/local/ssl -DCMAKE_JOB_POOL_COMPILE:STRING=compile -DCMAKE_JOB_POOL_LINK:STRING=link -DCMAKE_JOB_POOLS:STRING=compile=2;link=1'" \
  pipx run cibuildwheel --plat linux
```

**Comment by henryiii** [comment]
That is quite possible. If I can manually build and upload manylinux wheels we might be able to just go ahead with the cibuildwheel conversion and leave CircleCI behind?

**Comment by henryiii** [comment]
Would it be a good idea to move to pypa/setuptools_scm? It has nice tooling for this sort of thing; the manual versioner script doesn't have the nice overrides.

**Comment by henryiii** [comment]
Uploaded manylinux 3.20.2 wheels using cibuildwheel to build them locally off of the cibuildwheel branch.

> In the meantime, adding this is sensible.

Will do.

> We are currently versioneer, which problem would setuptools_scm address ?

Two problems. One is we have a lot of custom code (including `versioneer.py` and various workarounds), while setuptools_scm simply is a PyPI package. Second, with setuptools_scm, there are environment variable overrides (specifically, I needed `SETUPTOOLS_SCM_PRETEND_VERSION`) that can be used for emergency operations like this one. Also, it's a PyPA standard package instead of custom code.

**Comment by henryiii** [comment]
Technically, this is already closable, since the missing wheels are uploaded, but will officially close when I think we have fixed the CircleCI issue.
