### ISSUE TITLE
Cannot build cmake if package versioneer is installed

### ISSUE THREAD

**Issue by bennuttall** [scikit-build/cmake-python-distributions#171]
I tried to build cmake and I experienced this error:

```python
File "setup.py", line 33, in <module>
      version=versioneer.get_version(),
  AttributeError: module 'versioneer' has no attribute 'get_version'
```

I have the library [versioneer](https://pypi.org/project/versioneer/) installed it's importing that. But the versioneer module doesn't have a `get_version()` function.

I discovered is that `import versioneer` in cmake's [setup.py](https://github.com/scikit-build/cmake-python-distributions/blob/master/setup.py#L14) does not intend to import this library, it is supposed to import a file called [versioneer.py](https://github.com/scikit-build/cmake-python-distributions/blob/master/versioneer.py).

Unfortunately this means you can't build cmake if you have the library versioneer installed.

FYI I discovered this as it was reported that recent versions of cmake were missing from the [piwheels](https://www.piwheels.org/) index. The issue was reported here: https://github.com/piwheels/packages/issues/227

**Comment by mayeut** [comment]
> Unfortunately this means you can't build cmake if you have the library versioneer installed.

This should work well with build isolation. How is the wheel built ? where can we see logs ?
There's #143  to move from the custom versioneer script to setuptools_scm but that's on hold for now.

**Comment by bennuttall** [comment]
Build log is here: https://paste.debian.net/1206146/

**Comment by mayeut** [comment]
Thanks for the log. Unfortunately, it does not show how pip is invoked & I guess something in there might help us reproduce/understand the issue before fixing it (& check it's fixed).

**Comment by bennuttall** [comment]
The pip command we run is:

```
pip3 wheel cmake==3.21.1 --wheel-dir=wheel_dir --log=logfile--no-deps --no-cache-dir --no-binary=cmake --prefer-binary --exists-action=w --no-python-version-warning --disable-pip-version-check --index-url=https://pypi.python.org/simple --extra-index-url=https://www.piwheels.org/simple
```

**Comment by mayeut** [comment]
> The pip command we run is
Thanks.

I could not reproduce with:
```
pip wheel -v cmake==3.21.1 --wheel-dir=wheel_dir --log=logfile --no-deps --no-cache-dir --no-binary=cmake --prefer-binary --exists-action=w --no-python-version-warning --disable-pip-version-check
```
but I could with the following which I suspected:
```
pip wheel -v cmake==3.21.1 --wheel-dir=wheel_dir --log=logfile --no-deps --no-cache-dir --no-binary=cmake --prefer-binary --exists-action=w --no-python-version-warning --disable-pip-version-check --no-build-isolation
```

============

with the following `pip.conf`
```
[global]
no-build-isolation = false
```
or the following environment variable
```
PIP_NO_BUILD_ISOLATION=false
```

```
 pip wheel -v cmake==3.21.1 --wheel-dir=wheel_dir --log=logfile --no-deps --no-cache-dir --no-binary=cmake --prefer-binary --exists-action=w --no-python-version-warning --disable-pip-version-check
```
fails as well which suggest one or the other is probably used on your builder.
It's worth noting that the behavior of either this conf or environment variable is opposite what it should be c.f. https://github.com/pypa/pip/issues/5735 so if your builder does indeed set one or the other, is that the expected behavior ?

I will nevertheless fix the issue for "--no-build-isolation" builds now that I can reproduce/verify it.

**Comment by bennuttall** [comment]
Thanks, I've tested building from github and it worked :+1:

**Comment by mayeut** [comment]
cmake 3.21.1.post1 is now available on PyPI with this fix.

**Comment by bennuttall** [comment]
Thanks! It's building now (will work through the ABIs one-by-one): https://www.piwheels.org/project/cmake/

(I built the last few versions myself and imported them)

**Comment by JanLahmann** [comment]
Thank you to both of you, @bennuttall and @mayeut !
FYI: I'm using this as part of a project that is building a functional model of the IBM Quantum Computer, based on Qiskit (IBM Quantum software framework), a Raspberry Pi and a 3D printed housing: http://rasqberry.org

**Comment by bennuttall** [comment]
Build successfully for all ABIs now :+1:
