### ISSUE TITLE
Support python 3.6

### ISSUE THREAD

**Issue by iceb0y** [scikit-build/cmake-python-distributions#18]

**Comment by thewtex** [comment]
There are not any 3.6 wheels.

*sdist* builds fail with:

```
    --------------------------------
    -- Trying "Visual Studio 14 2015 Win64" generator - success
    --------------------------------------------------------------------------------

    -- The CXX compiler identification is MSVC 19.0.24210.0
    -- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe
    -- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe -
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    -- ***************************************************
    -- Build CMake from source: OFF
    -- ***************************************************
    CMake Error at CMakeLists.txt:35 (include):
      include could not find load file:

        C:/Users/matt/AppData/Local/Temp/pip-build-ylmz7x1s/cmake/CMakeUrls.cmake


    CMake Error at CMakeLists.txt:42 (message):
      Failed to determine which archive to download: 'windows_source_url'
      variable is not defined
    Call Stack (most recent call first):
      CMakeLists.txt:53 (check_archive_var)
```

**Comment by blowekamp** [comment]
Does the cmake binary wheel really depend on the version of Python? The current file names are like `cmake-0.6.0-cp27-cp27m-win32.whl`  The file name components are documented in [PEP 0427](https://www.python.org/dev/peps/pep-0427/#file-name-convention). I would expect the `version tag` could be `py2.py3`, and then the abi tag to be `none`. That would give us a file name such as `cmake-0.6.0-py2.py3-none-win32.whl` if that was compiled with VS9 it should work just about every where.

There some information on how this may de done here: https://wheel.readthedocs.io/en/latest/

**Comment by jcfr** [comment]
> Does the cmake binary wheel really depend on the version of Python? 

It doesn't have to

If you have the recipe to build such wheels using a sample project based on setuptools only, we should be able to update this project and the ninja one.

Also happy to review PR :smile:

**Comment by jcfr** [comment]
@blowekamp Worth noting that on windows, we do not build CMake we repackage it into separate wheels. 

To avoid having so many package, I will try to build a universal wheel for windows.

**Comment by blowekamp** [comment]
I googled and read a bit. I didn't see an obvious way to specify that this binary is "universal". It may be work experimenting with just renaming the file. Or some post processing of a wheel to relabel it.

**Comment by jcfr** [comment]
Closing. This will be fixed by #21

**Comment by jcfr** [comment]
Just updated to 3.8.1 (See #25), will generate wheels based on the latest CMake

**Comment by jcfr** [comment]
All set. Packages with CMake 3.8.1  are now pip installable. See https://pypi.python.org/pypi/cmake/
