### ISSUE TITLE
Support for CMake 3.8

### ISSUE THREAD

**Issue by henryiii** [scikit-build/cmake-python-distributions#20]
CMake 3.8 is out, with native support for CUDA as a language. I'd love to see this updated to CMake 3.8.
Cheers!

**Comment by jcfr** [comment]
Makes sense 👍 

Instructions to update the version of CMake are available here: http://cmake-python-distributions.readthedocs.io/en/latest/update_cmake_version.html

If you would like, you could try to create a PR for update the version of CMake bundled in the wheels. If not, I will do it later.

**Comment by jcfr** [comment]
Et voila. Here it is. See https://github.com/scikit-build/cmake-python-distributions/pull/21

When the tests complete, I will merge and generate new wheels.

Have a good weekend, 
Jc

**Comment by henryiii** [comment]
Excellent, thank you!

**Comment by jcfr** [comment]
Closing. This will be fixed by #21

**Comment by jcfr** [comment]
Just updated to 3.8.1 (See #25), will generate wheels based on the latest CMake

**Comment by jcfr** [comment]
All set. Packages with CMake 3.8.1  are now pip installable. See https://pypi.python.org/pypi/cmake/
