### ISSUE TITLE
Problem Installing opencv using pip on Raspbian Docker Container

### ISSUE THREAD

**Issue by rv2442** [scikit-build/cmake-python-distributions#285]
# pip install opencv-python
Collecting opencv-python
  Using cached opencv-python-4.6.0.66.tar.gz (90.3 MB)
  Installing build dependencies ... error
  error: subprocess-exited-with-error

  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [80 lines of output]
      Ignoring numpy: markers 'python_version == "3.6" and platform_machine != "aarch64" and platform_machine != "arm64"' don't match your environment
      Ignoring numpy: markers 'python_version == "3.8" and platform_machine != "aarch64" and platform_machine != "arm64"' don't match your environment
      Ignoring numpy: markers 'python_version <= "3.9" and sys_platform == "linux" and platform_machine == "aarch64"' don't match your environment
      Ignoring numpy: markers 'python_version <= "3.9" and sys_platform == "darwin" and platform_machine == "arm64"' don't match your environment
      Ignoring numpy: markers 'python_version == "3.9" and platform_machine != "aarch64" and platform_machine != "arm64"' don't match your environment
      Ignoring numpy: markers 'python_version >= "3.10"' don't match your environment
      Collecting setuptools==59.2.0
        Using cached setuptools-59.2.0-py3-none-any.whl (952 kB)
      Collecting wheel==0.37.0
        Using cached wheel-0.37.0-py2.py3-none-any.whl (35 kB)
      Collecting cmake>=3.1
        Using cached cmake-3.24.1.1.tar.gz (33 kB)
        Installing build dependencies: started
        Installing build dependencies: finished with status 'done'
        Getting requirements to build wheel: started
        Getting requirements to build wheel: finished with status 'done'
        Preparing metadata (pyproject.toml): started
        Preparing metadata (pyproject.toml): finished with status 'done'
      Collecting pip
        Using cached pip-22.2.2-py3-none-any.whl (2.0 MB)
      Collecting scikit-build>=0.13.2
        Using cached scikit_build-0.15.0-py2.py3-none-any.whl (77 kB)
      Collecting numpy==1.14.5
        Using cached numpy-1.14.5.zip (4.9 MB)
        Preparing metadata (setup.py): started
        Preparing metadata (setup.py): finished with status 'done'
      Collecting distro
        Using cached distro-1.7.0-py3-none-any.whl (20 kB)
      Collecting packaging
        Using cached packaging-21.3-py3-none-any.whl (40 kB)
      Collecting pyparsing!=3.0.5,>=2.0.2
        Using cached pyparsing-3.0.9-py3-none-any.whl (98 kB)
      Using legacy 'setup.py install' for numpy, since package 'wheel' is not installed.
      Building wheels for collected packages: cmake
        Building wheel for cmake (pyproject.toml): started
        Building wheel for cmake (pyproject.toml): finished with status 'error'
        error: subprocess-exited-with-error

        × Building wheel for cmake (pyproject.toml) did not run successfully.
        │ exit code: 1
        ╰─> [33 lines of output]
              File "/tmp/pip-build-env-5b0tkycw/overlay/lib/python3.7/site-packages/skbuild/setuptools_wrap.py", line 613, in setup
                cmkr = cmaker.CMaker(cmake_executable)
              File "/tmp/pip-build-env-5b0tkycw/overlay/lib/python3.7/site-packages/skbuild/cmaker.py", line 141, in __init__
                self.cmake_version = get_cmake_version(self.cmake_executable)
              File "/tmp/pip-build-env-5b0tkycw/overlay/lib/python3.7/site-packages/skbuild/cmaker.py", line 96, in get_cmake_version
                "Problem with the CMake installation, aborting build. CMake executable is %s" % cmake_executable
            Traceback (most recent call last):

                =============================DEBUG ASSISTANCE=============================
                If you are seeing a compilation error please try the following steps to
                successfully install cmake:
                1) Upgrade to the latest pip and try again. This will fix errors for most
                   users. See: https://pip.pypa.io/en/stable/installing/#upgrading-pip
                2) If on Linux, with glibc < 2.12, you can set PIP_ONLY_BINARY=cmake in
                   order to retrieve the last manylinux1 compatible wheel.
                3) If on Linux, with glibc < 2.12, you can cap "cmake<3.23" in your
                   requirements in order to retrieve the last manylinux1 compatible wheel.
                4) Open an issue with the debug information that follows at
                   https://github.com/scikit-build/cmake-python-distributions/issues

                Python: 3.7.0
                platform: Linux-5.10.102.1-microsoft-standard-WSL2-armv7l-with-debian-9.13
                glibc: glibc 2.24
                machine: armv7l
                bits: 32
                pip: n/a
                setuptools: 65.3.0
                scikit-build: 0.15.0
                PEP517_BUILD_BACKEND=setuptools.build_meta
                =============================DEBUG ASSISTANCE=============================

            Problem with the CMake installation, aborting build. CMake executable is cmake
            [end of output]

        note: This error originates from a subprocess, and is likely not a problem with pip.
        ERROR: Failed building wheel for cmake
      Failed to build cmake
      ERROR: Could not build wheels for cmake, which is required to install pyproject.toml-based projects
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
#

**Comment by rv2442** [comment]
Python version: 3.7 
pip version: 22.2.2
GNU make version: 4.1

**Comment by mayeut** [comment]
cmake requires cmake to build from sources (there is still a bootstrapping issue #33). It also requires openssl-dev. You need to install both packages with apt for cmake to build.

**Comment by rv2442** [comment]
thanks

**Comment by BMatthai** [comment]
> cmake requires cmake to build from sources (there is still a bootstrapping issue #33). It also requires openssl-dev. You need to install both packages with apt for cmake to build.

What to you mean by "cmake requires cmake to build from sources". How to install both packages with apt inside my Dockerfile ?
