### ISSUE TITLE
Unsigned binary issues on macOS 13

### ISSUE THREAD

**Issue by henryiii** [scikit-build/cmake-python-distributions#301]
I'm not able to use the pip package on macOS 13 without fighting with unsigned binaries. Guessing something has changed for signing?

**Comment by mayeut** [comment]
I just ran into this following the update to macOS 13.
A diff with an extracted tar.gz shows some symbolic links are missing. Even with those created, it's still failing.
Overwriting the python package with the tar.gz one still fails with `cp -r` but succeeds with `cp -R` so my guess (without searching too much) is that this have to do with symbolic links & possibly some other file attributes which are just not working with zip.
I'm not sure there's an easy way out of this but maybe I'm wrong.
One way is to store the `tar.gz` as-is and extract it upon first usage to a specific location.

**Comment by mayeut** [comment]
Another option is to "unbundle" the app, seems to be working. I'll dig a bit more in that direction.
If I'm not mistaken, the whole App bundling is related to GUI stuff. If we only retrieve the bin/share/... subfolders, we might be good to go. I don't really know what problems we could run into doing this, @jcfr @thewtex any idea ?
