### ISSUE TITLE
Source distribution should bootstrap CMake

### ISSUE THREAD

**Issue by ghost** [scikit-build/cmake-python-distributions#33]
CMake allows bootstrapping from source (with just autotools/GNU Make). Because this package is often the only method to get a new CMake with just `pip` available, I think it would be too difficult to add logic that would bootstrap a release CMake before calling scikit-build if CMake wasn't found on the path.

This would essentially be:

```python
if is_unix and not which('cmake'):
    download_extract('cmake.tar.gz')
    run('./bootstrap --prefix={prefix} && make && make install')
    os.environ['PATH'] += '{prefix}'
```

**Comment by mayeut** [comment]
implemented in #568
