### ISSUE TITLE
Provide CMake 3.11

### ISSUE THREAD

**Issue by henryiii** [scikit-build/cmake-python-distributions#34]
Pip install is a great way to suggest someone get a new CMake version; it would be great if 3.11 was available here too.

**Comment by jcfr** [comment]
All set. Thanks to @anthrotype , the version has been updated.

xref https://github.com/scikit-build/cmake-python-distributions/commit/01b535813c9df21c8d14db08cfa5da4f73854849

See https://pypi.org/project/cmake/
