### ISSUE TITLE
OpenCV installation with pip fails 'while building with cmake'

### ISSUE THREAD

**Issue by philipprsch** [scikit-build/cmake-python-distributions#392]
`Scanning dependencies of target cmake
    [ 89%] Building CXX object Source/CMakeFiles/cmake.dir/cmakemain.cxx.o
    [ 90%] Building CXX object Source/CMakeFiles/cmake.dir/cmcmd.cxx.o
    [ 90%] Linking CXX executable ../bin/cmake
    /usr/bin/ld: libCMakeLib.a(cmDebuggerAdapter.cxx.o): in function `std::_Function_handler<void (void const*, std::function<void (dap::TypeInfo const*, void const*)> const&, std::function<void (dap::TypeInfo const*, dap::Error const&)> const&), dap::Session::registerHandler<cmDebugger::cmDebuggerAdapter::cmDebuggerAdapter(std::shared_ptr<cmDebugger::cmDebuggerConnection>, std::optional<std::shared_ptr<dap::Writer> >)::{lambda(dap::NextRequest const&)#10}, dap::NextRequest>(std::integral_constant::SignatureOf&&)::{lambda(void const*, std::function<void (dap::TypeInfo const*, void const*)> const&, std::function<void (dap::TypeInfo const*, dap::Error const&)> const&)#1}>::_M_invoke(std::_Any_data const&, void const*&&, std::function<void (dap::TypeInfo const*, void const*)> const&, std::function<void (dap::TypeInfo const*, dap::Error const&)> const&)':
    cmDebuggerAdapter.cxx:(.text+0x998): undefined reference to `__atomic_store_8'
    /usr/bin/ld: libCMakeLib.a(cmDebuggerAdapter.cxx.o): in function `std::_Function_handler<void (void const*, std::function<void (dap::TypeInfo const*, void const*)> const&, std::function<void (dap::TypeInfo const*, dap::Error const&)> const&), dap::Session::registerHandler<cmDebugger::cmDebuggerAdapter::cmDebuggerAdapter(std::shared_ptr<cmDebugger::cmDebuggerConnection>, std::optional<std::shared_ptr<dap::Writer> >)::{lambda(dap::StepOutRequest const&)#12}, dap::StepOutRequest>(std::integral_constant::SignatureOf&&)::{lambda(void const*, std::function<void (dap::TypeInfo const*, void const*)> const&, std::function<void (dap::TypeInfo const*, dap::Error const&)> const&)#1}>::_M_invoke(std::_Any_data const&, void const*&&, std::function<void (dap::TypeInfo const*, void const*)> const&, std::function<void (dap::TypeInfo const*, dap::Error const&)> const&)':
    cmDebuggerAdapter.cxx:(.text+0xab8): undefined reference to `__atomic_store_8'
    /usr/bin/ld: libCMakeLib.a(cmDebuggerAdapter.cxx.o): in function `std::_Function_handler<void (void const*, std::function<void (dap::TypeInfo const*, void const*)> const&, std::function<void (dap::TypeInfo const*, dap::Error const&)> const&), dap::Session::registerHandler<cmDebugger::cmDebuggerAdapter::cmDebuggerAdapter(std::shared_ptr<cmDebugger::cmDebuggerConnection>, std::optional<std::shared_ptr<dap::Writer> >)::{lambda(dap::DisconnectRequest const&)#14}, dap::DisconnectRequest>(std::integral_constant::SignatureOf&&)::{lambda(void const*, std::function<void (dap::TypeInfo const*, void const*)> const&, std::function<void (dap::TypeInfo const*, dap::Error const&)> const&)#1}>::_M_invoke(std::_Any_data const&, void const*&&, std::function<void (dap::TypeInfo const*, void const*)> const&, std::function<void (dap::TypeInfo const*, dap::Error const&)> const&)':
    cmDebuggerAdapter.cxx:(.text+0xbe4): undefined reference to `__atomic_store_8'
    /usr/bin/ld: cmDebuggerAdapter.cxx:(.text+0xc04): undefined reference to `__atomic_store_8'
    /usr/bin/ld: libCMakeLib.a(cmDebuggerAdapter.cxx.o): in function `std::_Function_handler<void (char const*), cmDebugger::cmDebuggerAdapter::cmDebuggerAdapter(std::shared_ptr<cmDebugger::cmDebuggerConnection>, std::optional<std::shared_ptr<dap::Writer> >)::{lambda(char const*)#1}>::_M_invoke(std::_Any_data const&, char const*&&)':
    cmDebuggerAdapter.cxx:(.text+0xe1c): undefined reference to `__atomic_store_8'
    /usr/bin/ld: libCMakeLib.a(cmDebuggerAdapter.cxx.o):cmDebuggerAdapter.cxx:(.text+0xe3c): more undefined references to `__atomic_store_8' follow
    /usr/bin/ld: libCMakeLib.a(cmDebuggerAdapter.cxx.o): in function `cmDebugger::cmDebuggerAdapter::OnBeginFunctionCall(cmMakefile*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, cmListFileFunction const&)':
    cmDebuggerAdapter.cxx:(.text+0x24e8): undefined reference to `__atomic_load_8'
    /usr/bin/ld: cmDebuggerAdapter.cxx:(.text+0x2524): undefined reference to `__atomic_store_8'
    /usr/bin/ld: cmDebuggerAdapter.cxx:(.text+0x2544): undefined reference to `__atomic_store_8'
    /usr/bin/ld: cmDebuggerAdapter.cxx:(.text+0x2750): undefined reference to `__atomic_store_8'
    /usr/bin/ld: cmDebuggerAdapter.cxx:(.text+0x2770): undefined reference to `__atomic_store_8'
    /usr/bin/ld: cmDebuggerAdapter.cxx:(.text+0x2848): undefined reference to `__atomic_load_8'
    /usr/bin/ld: libCMakeLib.a(cmDebuggerAdapter.cxx.o): in function `cmDebugger::cmDebuggerAdapter::cmDebuggerAdapter(std::shared_ptr<cmDebugger::cmDebuggerConnection>, std::optional<std::shared_ptr<dap::Writer> >)':
    cmDebuggerAdapter.cxx:(.text+0x543c): undefined reference to `__atomic_store_8'
    /usr/bin/ld: cmDebuggerAdapter.cxx:(.text+0x545c): undefined reference to `__atomic_store_8'
    /usr/bin/ld: libCMakeLib.a(cmDebuggerStackFrame.cxx.o): in function `cmDebugger::cmDebuggerStackFrame::cmDebuggerStackFrame(cmMakefile*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, cmListFileFunction const&)':
    cmDebuggerStackFrame.cxx:(.text+0x2c): undefined reference to `__atomic_fetch_add_8'
    /usr/bin/ld: libCMakeLib.a(cmDebuggerVariables.cxx.o): in function `cmDebugger::cmDebuggerVariables::cmDebuggerVariables(std::shared_ptr<cmDebugger::cmDebuggerVariablesManager>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool)':
    cmDebuggerVariables.cxx:(.text+0x30f0): undefined reference to `__atomic_fetch_add_8'
    /usr/bin/ld: libCMakeLib.a(cmDebuggerVariables.cxx.o): in function `cmDebugger::cmDebuggerVariables::cmDebuggerVariables(std::shared_ptr<cmDebugger::cmDebuggerVariablesManager>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, std::function<std::vector<cmDebugger::cmDebuggerVariableEntry, std::allocator<cmDebugger::cmDebuggerVariableEntry> > ()>)':
    cmDebuggerVariables.cxx:(.text+0x32b8): undefined reference to `__atomic_fetch_add_8'
    /usr/bin/ld: libCMakeLib.a(cmDebuggerThreadManager.cxx.o): in function `cmDebugger::cmDebuggerThreadManager::StartThread(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
    cmDebuggerThreadManager.cxx:(.text+0x23c): undefined reference to `__atomic_fetch_add_8'
    /usr/bin/ld: ../Utilities/cmcppdap/libcmcppdap.a(typeof.cpp.o): in function `(anonymous namespace)::TypeInfos::get()::Instance::~Instance()':
    typeof.cpp:(.text+0xd0): undefined reference to `__atomic_fetch_sub_8'
    /usr/bin/ld: ../Utilities/cmcppdap/libcmcppdap.a(typeof.cpp.o): in function `dap::initialize()':
    typeof.cpp:(.text+0x6c0): undefined reference to `__atomic_fetch_add_8'
    /usr/bin/ld: ../Utilities/cmcppdap/libcmcppdap.a(typeof.cpp.o): in function `dap::terminate()':
    typeof.cpp:(.text+0x6f0): undefined reference to `__atomic_fetch_sub_8'
    collect2: error: ld returned 1 exit status
    gmake[5]: *** [Source/CMakeFiles/cmake.dir/build.make:135: bin/cmake] Error 1
    gmake[4]: *** [CMakeFiles/Makefile2:2343: Source/CMakeFiles/cmake.dir/all] Error 2
    gmake[3]: *** [Makefile:182: all] Error 2
    gmake[2]: *** [CMakeFiles/CMakeProject-build.dir/build.make:134: CMakeProject-build-prefix/src/CMakeProject-build-stamp/CMakeProject-build-build] Error 2
    gmake[1]: *** [CMakeFiles/Makefile2:127: CMakeFiles/CMakeProject-build.dir/all] Error 2
    gmake: *** [Makefile:149: all] Error 2
    Traceback (most recent call last):
      File "/tmp/pip-build-env-n3td43xg/overlay/lib/python3.9/site-packages/skbuild/setuptools_wrap.py", line 674, in setup
        cmkr.make(make_args, install_target=cmake_install_target, env=env)
      File "/tmp/pip-build-env-n3td43xg/overlay/lib/python3.9/site-packages/skbuild/cmaker.py", line 697, in make
        self.make_impl(clargs=clargs, config=config, source_dir=source_dir, install_target=install_target, env=env)
      File "/tmp/pip-build-env-n3td43xg/overlay/lib/python3.9/site-packages/skbuild/cmaker.py", line 742, in make_impl
        raise SKBuildError(msg)

        =============================DEBUG ASSISTANCE=============================
        If you are seeing a compilation error please try the following steps to
        successfully install cmake:
        1) Upgrade to the latest pip and try again. This will fix errors for most
           users. See: https://pip.pypa.io/en/stable/installing/#upgrading-pip
        2) If on Linux, with glibc < 2.12, you can set PIP_ONLY_BINARY=cmake in
           order to retrieve the last manylinux1 compatible wheel.
        3) If on Linux, with glibc < 2.12, you can cap "cmake<3.23" in your
           requirements in order to retrieve the last manylinux1 compatible wheel.
        4) Open an issue with the debug information that follows at
           https://github.com/scikit-build/cmake-python-distributions/issues

        Python: 3.9.2
        platform: Linux-6.1.21-v8+-aarch64-with-glibc2.31
        glibc: glibc 2.31
        machine: aarch64
        bits: 32
        pip: n/a
        setuptools: 68.0.0
        scikit-build: 0.17.6
        PEP517_BUILD_BACKEND=setuptools.build_meta
        =============================DEBUG ASSISTANCE=============================

    An error occurred while building with CMake.
      Command:
        /usr/bin/cmake --build . --target install --config Release --
      Install target:
        install
      Source directory:
        /tmp/pip-install-uquov4jt/cmake_62d414c29a2e4fb9be15789416297c78
      Working directory:
        /tmp/pip-install-uquov4jt/cmake_62d414c29a2e4fb9be15789416297c78/_skbuild/linux-aarch64-3.9/cmake-build
    Please check the install target is valid and see CMake's output for more information.

    error: subprocess-exited-with-error

    × Building wheel for cmake (pyproject.toml) did not run successfully.
    │ exit code: 1
    ╰─> See above for output.

    note: This error originates from a subprocess, and is likely not a problem with pip.
    full command: /home/pi/Documents/PythonFaceDetection/env/bin/python /home/pi/Documents/PythonFaceDetection/env/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py build_wheel /tmp/tmp5rpytgrv
    cwd: /tmp/pip-install-uquov4jt/cmake_62d414c29a2e4fb9be15789416297c78
    Building wheel for cmake (pyproject.toml): finished with status 'error'
    ERROR: Failed building wheel for cmake
  Failed to build cmake
  ERROR: Could not build wheels for cmake, which is required to install pyproject.toml-based projects
  error: subprocess-exited-with-error
  
  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  full command: /home/pi/Documents/PythonFaceDetection/env/bin/python /home/pi/Documents/PythonFaceDetection/env/lib/python3.9/site-packages/pip/__pip-runner__.py install --ignore-installed --no-user --prefix /tmp/pip-build-env-50mxrh5y/overlay --no-warn-script-location -v --no-binary :none: --only-binary :none: -i https://pypi.org/simple --extra-index-url https://www.piwheels.org/simple -- 'cmake>=3.1' 'numpy==1.13.3; python_version=='"'"'3.6'"'"' and platform_machine != '"'"'aarch64'"'"' and platform_machine != '"'"'arm64'"'"'' 'numpy==1.17.0; python_version=='"'"'3.7'"'"' and platform_machine != '"'"'aarch64'"'"' and platform_machine != '"'"'arm64'"'"'' 'numpy==1.17.5; python_version=='"'"'3.8'"'"' and platform_machine != '"'"'aarch64'"'"' and platform_machine != '"'"'arm64'"'"'' 'numpy==1.19.3; python_version<='"'"'3.9'"'"' and sys_platform == '"'"'linux'"'"' and platform_machine == '"'"'aarch64'"'"'' 'numpy==1.21.0; python_version<='"'"'3.9'"'"' and sys_platform == '"'"'darwin'"'"' and platform_machine == '"'"'arm64'"'"'' 'numpy==1.19.3; python_version=='"'"'3.9'"'"' and platform_machine != '"'"'aarch64'"'"' and platform_machine != '"'"'arm64'"'"'' 'numpy==1.21.2; python_version=='"'"'3.10'"'"' and platform_system!='"'"'Darwin'"'"'' 'numpy==1.21.4; python_version=='"'"'3.10'"'"' and platform_system=='"'"'Darwin'"'"'' 'numpy==1.22.2; python_version>='"'"'3.11'"'"'' pip 'scikit-build>=0.14.0' setuptools==59.2.0
  cwd: [inherit]
  Installing build dependencies ... error
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
Exception information:
Traceback (most recent call last):
  File "/home/pi/Documents/PythonFaceDetection/env/lib/python3.9/site-packages/pip/_internal/cli/base_command.py", line 180, in exc_logging_wrapper
    status = run_func(*args)
  File "/home/pi/Documents/PythonFaceDetection/env/lib/python3.9/site-packages/pip/_internal/cli/req_command.py", line 248, in wrapper
    return func(self, options, args)
  File "/home/pi/Documents/PythonFaceDetection/env/lib/python3.9/site-packages/pip/_internal/commands/install.py", line 377, in run
    requirement_set = resolver.resolve(
  File "/home/pi/Documents/PythonFaceDetection/env/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 92, in resolve
    result = self._result = resolver.resolve(
  File "/home/pi/Documents/PythonFaceDetection/env/lib/python3.9/site-packages/pip/_vendor/resolvelib/resolvers.py", line 546, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/home/pi/Documents/PythonFaceDetection/env/lib/python3.9/site-packages/pip/_vendor/resolvelib/resolvers.py", line 397, in resolve
    self._add_to_criteria(self.state.criteria, r, parent=None)
  File "/home/pi/Documents/PythonFaceDetection/env/lib/python3.9/site-packages/pip/_vendor/resolvelib/resolvers.py", line 173, in _add_to_criteria
    if not criterion.candidates:
  File "/home/pi/Documents/PythonFaceDetection/env/lib/python3.9/site-packages/pip/_vendor/resolvelib/structs.py", line 156, in __bool__
    return bool(self._sequence)
  File "/home/pi/Documents/PythonFaceDetection/env/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 155, in __bool__
    return any(self)
  File "/home/pi/Documents/PythonFaceDetection/env/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 143, in <genexpr>
    return (c for c in iterator if id(c) not in self._incompatible_ids)
  File "/home/pi/Documents/PythonFaceDetection/env/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 47, in _iter_built
    candidate = func()
  File "/home/pi/Documents/PythonFaceDetection/env/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 206, in _make_candidate_from_link
    self._link_candidate_cache[link] = LinkCandidate(
  File "/home/pi/Documents/PythonFaceDetection/env/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 293, in __init__
    super().__init__(
  File "/home/pi/Documents/PythonFaceDetection/env/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 156, in __init__
    self.dist = self._prepare()
  File "/home/pi/Documents/PythonFaceDetection/env/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 225, in _prepare
    dist = self._prepare_distribution()
  File "/home/pi/Documents/PythonFaceDetection/env/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 304, in _prepare_distribution
    return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
  File "/home/pi/Documents/PythonFaceDetection/env/lib/python3.9/site-packages/pip/_internal/operations/prepare.py", line 538, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
  File "/home/pi/Documents/PythonFaceDetection/env/lib/python3.9/site-packages/pip/_internal/operations/prepare.py", line 653, in _prepare_linked_requirement
    dist = _get_prepared_distribution(
  File "/home/pi/Documents/PythonFaceDetection/env/lib/python3.9/site-packages/pip/_internal/operations/prepare.py", line 69, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(
  File "/home/pi/Documents/PythonFaceDetection/env/lib/python3.9/site-packages/pip/_internal/distributions/sdist.py", line 38, in prepare_distribution_metadata
    self._prepare_build_backend(finder)
  File "/home/pi/Documents/PythonFaceDetection/env/lib/python3.9/site-packages/pip/_internal/distributions/sdist.py", line 70, in _prepare_build_backend
    self.req.build_env.install_requirements(
  File "/home/pi/Documents/PythonFaceDetection/env/lib/python3.9/site-packages/pip/_internal/build_env.py", line 217, in install_requirements
    self._install_requirements(
  File "/home/pi/Documents/PythonFaceDetection/env/lib/python3.9/site-packages/pip/_internal/build_env.py", line 275, in _install_requirements
    call_subprocess(
  File "/home/pi/Documents/PythonFaceDetection/env/lib/python3.9/site-packages/pip/_internal/utils/subprocess.py", line 224, in call_subprocess
    raise error
pip._internal.exceptions.InstallationSubprocessError: pip subprocess to install build dependencies exited with 1
Remote version of pip: 23.2.1
Local version of pip:  23.2.1
Was pip installed by pip? True
Removed opencv-python from https://files.pythonhosted.org/packages/32/72/03747a6820bc970aeb0b89e653d1084068ac1ed606a83d8b5ac6fc237c14/opencv-python-4.8.0.76.tar.gz from build tracker '/tmp/pip-build-tracker-aqys2nl1'
Removed build tracker: '/tmp/pip-build-tracker-aqys2nl1'`

Recently I keep getting this error when trying to install OpenCV with pip (Version: 23.2.1) in Python (Version: 3.9.2) on my Raspberry Pi 4B, with a freshly installed Raspberry OS.
I have tried updating pip and setuptools (to version 68.0.0) and have tried installing various packages with apt, as suggested by people facing similar issues but nothing so has resolved the problem. Above I have posted the console output that was generated after running `pip -vvv install opencv-python`, having verbose output enabled.
Any help or suggestions on how to resolve the problem would be very much appreciated.

**Comment by mayeut** [comment]
This looks like the same error as seen in piwheels for cmake>=3.27.0.
I guess rebuilding cmake 3.27+ (not this package but upstream cmake) from source fails as well in which case it shall be reported upstream.
You can probably work around this issue by adding [piwheels](https://www.piwheels.org) index (if not already done) and doing:
```
export PIP_ONLY_BINARY=cmake
```

**Comment by philipprsch** [comment]
Hi, thank you for your quick response. Could you please explain by 'adding piwheels index' and 'doing export PIP_ONLY_BINARY=cmake'. I'm sorry if I am asking you to elaborate things that should be obvious but as a beginner I only have a shallow understanding of what the above mean. Thank you.

**Comment by mayeut** [comment]
> Could you please explain by 'adding piwheels index'

Given your logs, you seem to already have this enabled. I nevertheless encourage you to visit [piwheels](https://www.piwheels.org)

> and 'doing export PIP_ONLY_BINARY=cmake'

instead of running `pip -vvv install opencv-python` run:
```
export PIP_ONLY_BINARY=cmake
pip -vvv install opencv-python
```

As a beginner, you might not want to build open-python from sources, piwheels also have [some pre-built wheels](https://www.piwheels.org/project/opencv-python/) (not the latest ones) for that so you can use [pip `--prefer-binary`](https://pip.pypa.io/en/stable/cli/pip_install/#cmdoption-prefer-binary) option:
```
pip install --prefer-binary opencv-python
```

**Comment by wuboy19** [comment]
[1029/1087] Linking CXX executable bin/cpack
        FAILED: bin/cpack
        : && /usr/bin/c++ -O3 -DNDEBUG -lstdc++ -lgcc -lrt Source/CMakeFiles/cpack.dir/CPack/cpack.cxx.o -o bin/cpack  Source/libCPackLib.a  Source/libCMakeLib.a  Utilities/std/libcmstd.a  Source/kwsys/libcmsys.a  Utilities/cmcurl/lib/libcmcurl.a  Utilities/cmnghttp2/libcmnghttp2.a  Utilities/cmexpat/libcmexpat.a  Utilities/cmlibarchive/libarchive/libcmlibarchive.a  /usr/lib/riscv64-linux-gnu/libssl.so  /usr/lib/riscv64-linux-gnu/libcrypto.so  Utilities/cmbzip2/libcmbzip2.a  Utilities/cmliblzma/libcmliblzma.a  Utilities/cmzstd/libcmzstd.a  Utilities/cmlibrhash/libcmlibrhash.a  Utilities/cmlibuv/libcmlibuv.a  -ldl  -lrt  Utilities/cmzlib/libcmzlib.a  Utilities/cmcppdap/libcmcppdap.a  Utilities/cmjsoncpp/libcmjsoncpp.a && :
        /usr/bin/ld: Utilities/cmcppdap/libcmcppdap.a(io.cpp.o): in function `.L0 ':
        io.cpp:(.text+0x138): undefined reference to `__atomic_exchange_1'
        /usr/bin/ld: io.cpp:(.text+0x5d4): undefined reference to `__atomic_exchange_1'
        /usr/bin/ld: io.cpp:(.text+0x624): undefined reference to `__atomic_exchange_1'
        /usr/bin/ld: io.cpp:(.text+0x676): undefined reference to `__atomic_exchange_1'
        /usr/bin/ld: io.cpp:(.text+0x6e2): undefined reference to `__atomic_exchange_1'
        /usr/bin/ld: Utilities/cmcppdap/libcmcppdap.a(io.cpp.o):io.cpp:(.text+0x74a): more undefined references to `__atomic_exchange_1' follow
        collect2: error: ld returned 1 exit status
        [1030/1087] Linking CXX static library Source/libCTestLib.a
        [1031/1087] Building CXX object Tests/CMakeLib/PseudoMemcheck/CMakeFiles/pseudo_valgrind.dir/ret0.cxx.o
        [1032/1087] Building CXX object Tests/CMakeLib/PseudoMemcheck/CMakeFiles/pseudo_purify.dir/ret0.cxx.o
        [1033/1087] Building CXX object Tests/CMakeLib/CMakeFiles/runcompilecommands.dir/run_compile_commands.cxx.o
        [1034/1087] Building CXX object Tests/CMakeLib/CMakeFiles/CMakeLibTests.dir/testString.cxx.o
        [1035/1087] Building CXX object Tests/CMakeLib/PseudoMemcheck/CMakeFiles/pseudo_BC.dir/ret0.cxx.o
        [1036/1087] Linking CXX executable bin/cmake
        FAILED: bin/cmake
        : && /usr/bin/c++ -O3 -DNDEBUG -lstdc++ -lgcc -lrt Source/CMakeFiles/cmake.dir/cmakemain.cxx.o Source/CMakeFiles/cmake.dir/cmcmd.cxx.o -o bin/cmake  Source/libCMakeLib.a  Utilities/std/libcmstd.a  Source/kwsys/libcmsys.a  Utilities/cmcurl/lib/libcmcurl.a  Utilities/cmnghttp2/libcmnghttp2.a  Utilities/cmexpat/libcmexpat.a  Utilities/cmlibarchive/libarchive/libcmlibarchive.a  /usr/lib/riscv64-linux-gnu/libssl.so  /usr/lib/riscv64-linux-gnu/libcrypto.so  Utilities/cmbzip2/libcmbzip2.a  Utilities/cmliblzma/libcmliblzma.a  Utilities/cmzstd/libcmzstd.a  Utilities/cmlibrhash/libcmlibrhash.a  Utilities/cmlibuv/libcmlibuv.a  -ldl  -lrt  Utilities/cmzlib/libcmzlib.a  Utilities/cmcppdap/libcmcppdap.a  Utilities/cmjsoncpp/libcmjsoncpp.a && :
        /usr/bin/ld: Utilities/cmcppdap/libcmcppdap.a(io.cpp.o): in function `.L0 ':
        io.cpp:(.text+0x138): undefined reference to `__atomic_exchange_1'
        /usr/bin/ld: io.cpp:(.text+0x5d4): undefined reference to `__atomic_exchange_1'
        /usr/bin/ld: io.cpp:(.text+0x624): undefined reference to `__atomic_exchange_1'
        /usr/bin/ld: io.cpp:(.text+0x676): undefined reference to `__atomic_exchange_1'
        /usr/bin/ld: io.cpp:(.text+0x6e2): undefined reference to `__atomic_exchange_1'
        /usr/bin/ld: Utilities/cmcppdap/libcmcppdap.a(io.cpp.o):io.cpp:(.text+0x74a): more undefined references to `__atomic_exchange_1' follow
        collect2: error: ld returned 1 exit status
        [1037/1087] Building CXX object Tests/CMakeLib/CMakeFiles/CMakeLibTests.dir/testJSONHelpers.cxx.o
        [1038/1087] Building CXX object Tests/CMakeLib/PseudoMemcheck/CMakeFiles/pseudo_cuda-memcheck.dir/ret0.cxx.o
        [1039/1087] Building CXX object Tests/CMakeLib/PseudoMemcheck/CMakeFiles/memcheck_fail.dir/ret1.cxx.o
        [1040/1087] Building CXX object Tests/CMakeLib/CMakeFiles/testDebuggerNamedPipe.dir/testDebuggerNamedPipe.cxx.o
        [1041/1087] Building CXX object Tests/CMakeLib/CMakeFiles/CMakeLibTests.dir/testDebuggerVariables.cxx.o
        [1042/1087] Building CXX object Tests/CMakeLib/CMakeFiles/CMakeLibTests.dir/testList.cxx.o
        [1043/1087] Building CXX object Tests/CMakeLib/CMakeFiles/CMakeLibTests.dir/testDebuggerAdapterPipe.cxx.o
        [1044/1087] Building CXX object Tests/CMakeLib/CMakeFiles/CMakeLibTests.dir/testDebuggerAdapter.cxx.o
        [1045/1087] Building CXX object Tests/CMakeLib/CMakeFiles/CMakeLibTests.dir/testDebuggerBreakpointManager.cxx.o
        [1046/1087] Building CXX object Tests/CMakeLib/CMakeFiles/CMakeLibTests.dir/testDebuggerVariablesHelper.cxx.o
        ninja: build stopped: subcommand failed.
        FAILED: CMakeProject-build-prefix/src/CMakeProject-build-stamp/CMakeProject-build-build /tmp/pip-install-hh0dkb1n/cmake_d27e89113df44da58d02dbedb5781671/_skbuild/linux-riscv64-3.11/cmake-build/CMakeProject-build-prefix/src/CMakeProject-build-stamp/CMakeProject-build-build
        cd /tmp/pip-install-hh0dkb1n/cmake_d27e89113df44da58d02dbedb5781671/_skbuild/linux-riscv64-3.11/cmake-build/CMakeProject-build && /usr/bin/cmake --build .
        ninja: build stopped: subcommand failed.
        Traceback (most recent call last):
          File "/tmp/pip-build-env-1bydd0sl/overlay/lib/python3.11/site-packages/skbuild/setuptools_wrap.py", line 674, in setup
            cmkr.make(make_args, install_target=cmake_install_target, env=env)
          File "/tmp/pip-build-env-1bydd0sl/overlay/lib/python3.11/site-packages/skbuild/cmaker.py", line 697, in make
            self.make_impl(clargs=clargs, config=config, source_dir=source_dir, install_target=install_target, env=env)
          File "/tmp/pip-build-env-1bydd0sl/overlay/lib/python3.11/site-packages/skbuild/cmaker.py", line 742, in make_impl
            raise SKBuildError(msg)


            =============================DEBUG ASSISTANCE=============================
            If you are seeing a compilation error please try the following steps to
            successfully install cmake:
            1) Upgrade to the latest pip and try again. This will fix errors for most
               users. See: https://pip.pypa.io/en/stable/installing/#upgrading-pip
            2) If on Linux, with glibc < 2.12, you can set PIP_ONLY_BINARY=cmake in
               order to retrieve the last manylinux1 compatible wheel.
            3) If on Linux, with glibc < 2.12, you can cap "cmake<3.23" in your
               requirements in order to retrieve the last manylinux1 compatible wheel.
            4) Open an issue with the debug information that follows at
               https://github.com/scikit-build/cmake-python-distributions/issues

            Python: 3.11.4
            platform: Linux-5.15.90.1-microsoft-standard-WSL2-riscv64-with-glibc2.37
            glibc: glibc 2.37
            machine: riscv64
            bits: 64
            pip: n/a
            setuptools: 68.2.2
            scikit-build: 0.17.6
            PEP517_BUILD_BACKEND=setuptools.build_meta
            =============================DEBUG ASSISTANCE=============================

        An error occurred while building with CMake.
          Command:
            /usr/bin/cmake --build . --target install --config Release --
          Install target:
            install
          Source directory:
            /tmp/pip-install-hh0dkb1n/cmake_d27e89113df44da58d02dbedb5781671
          Working directory:
            /tmp/pip-install-hh0dkb1n/cmake_d27e89113df44da58d02dbedb5781671/_skbuild/linux-riscv64-3.11/cmake-build
        Please check the install target is valid and see CMake's output for more information.

        [end of output]

    note: This error originates from a subprocess, and is likely not a problem with pip.
    ERROR: Failed building wheel for cmake
  Failed to build cmake
  ERROR: Could not build wheels for cmake, which is required to install pyproject.toml-based projects
  error: subprocess-exited-with-error
  
  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  full command: /root/py311/bin/python3 /root/py311/lib/python3.11/site-packages/pip/__pip-runner__.py install --ignore-installed --no-user --prefix /tmp/pip-build-env-t45mc3k2/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools==59.2.0 wheel==0.37.0 'cmake>=3.1' pip 'scikit-build>=0.13.2' 'numpy==1.13.3; python_version=='"'"'3.6'"'"' and platform_machine != '"'"'aarch64'"'"' and platform_machine != '"'"'arm64'"'"'' 'numpy==1.17.0; python_version=='"'"'3.7'"'"' and platform_machine != '"'"'aarch64'"'"' and platform_machine != '"'"'arm64'"'"'' 'numpy==1.17.5; python_version=='"'"'3.8'"'"' and platform_machine != '"'"'aarch64'"'"' and platform_machine != '"'"'arm64'"'"'' 'numpy==1.19.3; python_version<='"'"'3.9'"'"' and sys_platform == '"'"'linux'"'"' and platform_machine == '"'"'aarch64'"'"'' 'numpy==1.21.0; python_version<='"'"'3.9'"'"' and sys_platform == '"'"'darwin'"'"' and platform_machine == '"'"'arm64'"'"'' 'numpy==1.19.3; python_version=='"'"'3.9'"'"' and platform_machine != '"'"'aarch64'"'"' and platform_machine != '"'"'arm64'"'"'' 'numpy==1.21.2; python_version=='"'"'3.10'"'"' and platform_system!='"'"'Darwin'"'"'' 'numpy==1.21.4; python_version=='"'"'3.10'"'"' and platform_system=='"'"'Darwin'"'"'' 'numpy==1.23.2; python_version>='"'"'3.11'"'"''
  cwd: [inherit]
  Installing build dependencies ... error
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by mayeut** [comment]
Related to upstream issue https://gitlab.kitware.com/cmake/cmake/-/issues/25204
Fixed in https://gitlab.kitware.com/cmake/cmake/-/commit/8708b41532a01479a96b2d5a67e54b7a1397306f
