### ISSUE TITLE
[ERROR] ]Problem with the CMake installation, aborting build. CMake executable is cmake

### ISSUE THREAD

**Issue by enyoos** [scikit-build/cmake-python-distributions#427]
Python: 3.10.8
platform: Windows-10-10.0.22621-SP0
machine: AMD64
bits: 64
pip: n/a
setuptools: 69.0.2
scikit-build: 0.17.6
PEP517_BUILD_BACKEND=setuptools.build_meta

**Comment by enyoos** [comment]
nvm, can someone close this issue, appreciate it.

**Comment by motcke** [comment]
I'm having the same issue:
```
          Python: 3.10.12
          platform: Windows-10-10.0.22631-SP0
          machine: AMD64
          bits: 64
          pip: n/a
          setuptools: 69.0.2
          scikit-build: 0.17.6
          PEP517_BUILD_BACKEND=setuptools.build_meta
```
@enyoos did you solve it? how?

**Comment by motcke** [comment]
eventually, I installed Python 3.12.0 using pyenv-win and everything was installed successfully

**Comment by enyoos** [comment]
> eventually, I installed Python 3.12.0 using pyenv-win and everything was installed successfully

Can you give me the command executed on your terminal ( cmd ). Thanks.
