### ISSUE TITLE
Wheels still tagged as Python 2-compatible

### ISSUE THREAD

**Issue by YannickJadoul** [scikit-build/cmake-python-distributions#459]
The wheels on PyPI have names like `cmake-3.28.3-py2.py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl`, which include `py2`. However, wheels are not Python 2 compatible (anymore), given that `_version.py` contains (generated by `setuptools-scm`) type annotations.

Python 2 should be dead and buried, but you might still want to at least fix the wheel names to not be lying?

**Comment by henryiii** [comment]
I've pushed a final Py2 release of 3.28.4. 3.29.0 will switch to scikit-build-core and require Python 3.7+.

Good to see Python 2 is so dead that no one noticed this for quite a while!

**Comment by jcfr** [comment]
Thanks @YannickJadoul for bringing this up and @henryiii for working on a fix :pray:
