### ISSUE TITLE
Missing dependency on importlib_metadata

### ISSUE THREAD

**Issue by roastduck** [scikit-build/cmake-python-distributions#471]
#455 brought a new dependency on `importlib_metadata` for Python < 3.10 in `src/cmake/__init__.py`. The dependency in `pyproject.toml` was set as `optional`, but it seems necessary. Missing such a dependency results in the following error:

```
ModuleNotFoundError: No module named 'importlib_metadata'
```

**Comment by agriyakhetarpal** [comment]
Oops, I just opened #472 for the same thing :)

**Comment by henryiii** [comment]
For some reason the other issues seems to have received more comments, so will close this one as a dup of that one, even though it's reversed. :) 3.29.0 is yanked and we'll produce a 3.29.0.1 later today.

**Comment by henryiii** [comment]
New version out!
