### ISSUE TITLE
cmake 3.31 is broken: CMake Error: Could not find CMAKE_ROOT !!!

### ISSUE THREAD

**Issue by njzjz** [scikit-build/cmake-python-distributions#557]
See this error in the CI, which can be reproduced:

```
CMake Error: Could not find CMAKE_ROOT !!!
CMake has most likely not been installed correctly.
Modules directory not found in
/usr/local/share/cmake-3.31
CMake Error: Error executing cmake::LoadCache(). Aborting.
```

reproduce:
https://gist.github.com/njzjz/1c8f360ebc4457bf0d0f6ea86978b78b

CI log: https://github.com/deepmodeling/deepmd-kit/actions/runs/11758764445/job/32757483294#step:3:1

**Comment by henryiii** [comment]
I’d be fine to yank this while we figure it out, but it doesn’t seem like I have permission to yank, @jcfr?

**Comment by Transurgeon** [comment]
can confirm we are getting this error too (from installing wheels for cvxpy->osqp->qdldl->cmake).

**Comment by Sytten** [comment]
Came here to say so, also can you guys link to this repo from pypi it was a pain to find it

**Comment by nucflash** [comment]
+1

**Comment by henryiii** [comment]
I don’t have permission to yank, so I’ll have to try to fix this tonight. I’m assuming it’ll show up on any system that does not have a system CMake (I.e, like ci or my machine)

**Comment by jcfr** [comment]
Yanking now.

**Comment by jcfr** [comment]
`3.31.0` yanked ✅️

--------

![Screenshot_20241109_211723_Chrome.jpg](https://github.com/user-attachments/assets/c8d45416-5a21-4dcc-ba46-99931b31ac05)

**Comment by henryiii** [comment]
Ah, wow, this only shows up if there's a CMakeLists.txt present. I hadn't realized that at first; my docker reproducer wasn't reproducing but adding the CMakeLists.txt does trigger it.

Got the bug. CMake's inspecting the first arg to find the root path. But in #555 I didn't give it the full path.

**Comment by henryiii** [comment]
@Sytten

>  also can you guys link to this repo from pypi it was a pain to find it

We have links pointing back here, both on PyPI:

https://github.com/scikit-build/cmake-python-distributions/blob/0c316e2d1a68b84ce5220fad05fe706848e670b0/pyproject.toml#L36

And in the readme:

https://github.com/scikit-build/cmake-python-distributions/blob/0c316e2d1a68b84ce5220fad05fe706848e670b0/README.rst?plain=1#L88-L90

Not sure where else we could add more links?

**Comment by henryiii** [comment]
New 3.31.0.1 release will be up a few hours.

**Comment by jcfr** [comment]
Thanks @henryiii for sorting this out 🙏💯
