### ISSUE TITLE
CMake 3.13

### ISSUE THREAD

**Issue by henryiii** [scikit-build/cmake-python-distributions#56]
Looks like 3.12.0 is the latest provided, but 3.13 is out...

**Comment by jcfr** [comment]
Indeed, this PR should address it. See https://github.com/scikit-build/cmake-python-distributions/pull/57

**Comment by henryiii** [comment]
Great. I was updating [the version table on Modern CMake](https://cliutils.gitlab.io/modern-cmake/chapters/intro/dodonot.html) and I'd like to see the pip method remain one of the best options!

**Comment by jcfr** [comment]
Repository has been tagged, release packages are now being built and should be available on PyPI shortly.

**Comment by henryiii** [comment]
Perfect! Thanks! Just updated my page to reflect that.
