### ISSUE TITLE
`pypy -m pip install cmake` fails

### ISSUE THREAD

**Issue by dhermes** [scikit-build/cmake-python-distributions#60]
```
$ pypy-venv/bin/pip install cmake
Collecting cmake
  Using cached https://files.pythonhosted.org/packages/ca/dd/b1df8148e52f94404979d879bf6fb763dc85a1c421729909b0089d22331f/cmake-3.13.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<module>", line 1, in <module>
      File "/tmp/pip-install-P2Cl5_/cmake/setup.py", line 7, in <module>
        from skbuild import setup
    ImportError: No module named skbuild

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-P2Cl5_/cmake/
```

**Comment by dhermes** [comment]
When `scikit-build` is present, it fails for different reasons:

```
$ pypy -m virtualenv pypy-venv
...
$ pypy-venv/bin/pip install scikit-build
...
Successfully installed packaging-18.0 pyparsing-2.3.0 scikit-build-0.8.1 six-1.12.0
$ pypy-venv/bin/pip install cmake
...
  Traceback (most recent call last):
    File "<module>", line 1, in <module>
    File "/tmp/pip-install-5AvaLq/cmake/setup.py", line 78, in <module>
      setup_requires=setup_requires
    File ".../pypy-venv/site-packages/skbuild/setuptools_wrap.py", line 548, in setup
      languages=cmake_languages
    File ".../pypy-venv/site-packages/skbuild/cmaker.py", line 203, in configure
      python_library),
  TypeError: unsupported operand type(s) for +: 'str' and 'NoneType'

  ----------------------------------------
  Failed building wheel for cmake
...
```

**Comment by jcfr** [comment]
Thanks for reporting the issue.

Waiting we need to address the issue reported in the second comment, is `pypy` always expected to build package from source ? Or should it download existing wheel ?

**Comment by jcfr** [comment]
I just released you tried to use http://doc.pypy.org. Similarly to cpython, is there prescribed docker images to use for building package on linux ?

**Comment by dhermes** [comment]
> is `pypy` always expected to build package from source ? Or should it download existing wheel ?

Looking at the [wheels][1] for `cmake`, they all have `cpXY-cpXYm[u]`. That `cp` stands for CPython. (AFAIK PyPI only allows uploading wheels for CPython.)

> I just released you tried to use http://doc.pypy.org.

I actually use `pyenv` to install my local version of `pypy`, but that shouldn't matter?

[1]: https://pypi.org/project/cmake/3.13.1/#files

**Comment by jcfr** [comment]
see https://github.com/scikit-build/scikit-build/pull/407

**Comment by thewtex** [comment]
Now that the `cmake` wheels are [using `py2-none` and `py3-none`](https://pypi.org/project/cmake/#files) instead of `cpXY-cpXYm[u]`, has this issue been addressed?

**Comment by henryiii** [comment]
Yes, it does! Just checked with pypy3 7.3.4. (On macOS, you still have to upgrade pip in the venv, as pypy ships with 20.1.1, which doesn't support wheels on Big Sur :angry: )
