### ISSUE TITLE
CMake 3.14

### ISSUE THREAD

**Issue by henryiii** [scikit-build/cmake-python-distributions#67]
CMake π seems to be missing...

**Comment by slurps-mad-rips** [comment]
Is there any update on this? It's a blocker for full VS2019 support :(

**Comment by jcfr** [comment]
Hi,

This should happen this week. Thanks for your patience.

Jc

**Comment by slurps-mad-rips** [comment]
Hi, I know you're probably busy as heck, and I do appreciate all the work that goes into this, but I just wanted to check in to see if there might be an update on when it might get released?

**Comment by jcfr** [comment]
Time flies. Thanks for the reminder :+1:

**Comment by jcfr** [comment]
This ended up taking longer than expected, good news is that the update to `3.14.3` is merged into master.

Before moving the release, this last issue will be addressed: https://github.com/scikit-build/cmake-python-distributions/issues/71

**Comment by slurps-mad-rips** [comment]
Hey this is great news! Not to be sore about it but apparently, [3.14.4][] fixes a moderately important bug.

Is there any set of info on how to help with the generation of these? I have extensive knowledge of CMake and Python and it might come in handy for this sort of thing.

[3.14.4]: https://cmake.org/cmake/help/latest/release/3.14.html#id3

**Comment by jcfr** [comment]
Thanks for offering help :pray: 

Would be great if you could review https://github.com/scikit-build/cmake-python-distributions/pull/72, once it is integrated, we will release 3.14.3. 

After that, you could submit a PR updating to 3.14.4 following [Updating the CMake version](https://cmake-python-distributions.readthedocs.io/en/latest/update_cmake_version.html)

**Comment by jcfr** [comment]
Update:
* generic  platform wheel for linux and macOS distributions have been uploaded
* there was an issue with the windows one ... pypi reported `Command executed with exception: HTTPError: 400 Client Error: Invalid distribution file. for url: https://upload.pypi.org/legacy/`
  * it turns out this was an issue with the `wheeltools` project. See https://github.com/anthrotype/wheeltools/pull/1
  * waiting the fix is integrated in upstream `wheeltools`, the cmake wheel have been manually generated and uploaded from appveyor build agent.

**Comment by jcfr** [comment]
![image](https://user-images.githubusercontent.com/219043/58393879-a6eda380-800e-11e9-86c5-cc8e58fe490b.png)

**Comment by jcfr** [comment]
@slurps-mad-rips CMake 3.14.4 is on the way ... see https://github.com/scikit-build/cmake-python-distributions/pull/75

**Comment by jcfr** [comment]
@slurps-mad-rips Et voila, 3.14.4 is available for manylinux2010. 

If you using manylinux docker image as a build environment, make sure you update from `manylinux1` to `manylinux2010`.

You may also be interested by https://github.com/dockcross/dockcross#cross-compilers

**Comment by jcfr** [comment]
![image](https://user-images.githubusercontent.com/219043/58397796-8dedee00-8020-11e9-84e9-fe752d52870f.png)
