### ISSUE TITLE
Add FAQ entry "Why is install failing with CMake >= 3.14 ?"

### ISSUE THREAD

**Issue by jcfr** [scikit-build/cmake-python-distributions#77]
See https://github.com/scikit-build/cmake-python-distributions/issues/76#issuecomment-496220781

**Comment by henryiii** [comment]
This was actually fixed some time ago, now that manylinux1 is provided again.

**Comment by jcfr** [comment]
Closing. This was fixed  in  https://github.com/scikit-build/cmake-python-distributions/pull/97
