### ISSUE TITLE
Revisit use of manylinux2010 to build wheel

### ISSUE THREAD

**Issue by jcfr** [scikit-build/cmake-python-distributions#78]
### Background:

We started building the cmake wheel using manylinux2010 because, the latest version of cmake couldn't be built using manylinux1.

At first, only providing manylinux2010 wheel for the latest cmake was preventing `pip install cmake` done from a manylinux1 environment from downloading the latest wheel available for that platform, indeed, by default, pip prefer building the latest sdist instead of downloading the latest wheel for that platform. This is discussed in https://github.com/pypa/pip/issues/6550. 

For an example of project that faced that problem, see equinor/dlisio#116 and https://github.com/scikit-build/cmake-python-distributions/issues/76

To address, this, the sdist associated with cmake 3.14.3 and 3.14.4 were removed from pypi (note that sdist of 3.13.3 was also removed but this was not strictly required).

### Next step

As suggested in https://gitlab.kitware.com/cmake/cmake/issues/19311, we could look into building cmake against a version of an older libuv library built on manylinux1.

**Comment by filipArena** [comment]
I'm having trouble using scikit-build / cmake with Python 3.8. Even latest pip 19 refuses to install the manylinux2010 wheel and tries to install a sdist.

**Comment by henryiii** [comment]
@jfcr, fyi, I provide manylinux1 wheels for boost-histogram, which requires C++14, and is built with https://github.com/scikit-hep/azure-wheel-helpers and GCC 9.2 from https://github.com/scikit-hep/manylinuxgcc (docker container). It wouldn't be valid to link to from another manylinux1 wheel unless it also was built with GCC 9, but no one is linking to CMake, so something like that might be an option for a manylinux1 compliant wheel. Just a thought.

**Comment by jcfr** [comment]
> can't a system libUV from CentOS 5 be bundled in?

Yes, I just tested that approach. Building against libuv 1.23.0 prior https://github.com/libuv/libuv/commit/f43c66343316878da09949daf49b515249f71bdf and it seems to works well. 

I will create new releases of existing cmake wheels (with `.post1` suffix where relevant) that are working on manylinux1

**Comment by jcfr** [comment]
For future reference:
* [3.14.3.post1](https://github.com/scikit-build/cmake-python-distributions/releases/tag/3.14.3.post1)
* [3.14.4.post1](https://github.com/scikit-build/cmake-python-distributions/releases/tag/3.14.4.post1)
* [3.15.3.post1](https://github.com/scikit-build/cmake-python-distributions/releases/tag/3.15.3.post1)
* [3.16.3.post1](https://github.com/scikit-build/cmake-python-distributions/releases/tag/3.16.3.post1)
