### ISSUE TITLE
CMake 3.15?

### ISSUE THREAD

**Issue by henryiii** [scikit-build/cmake-python-distributions#81]
Is updating this in the plans? Let me know if there's something I can do to help.

**Comment by jcfr** [comment]
Hi Henry,

I am travelling until the end of the month and won't have time to release
new wheels.

In the mean time, it would be helpful if you could create a new PR.

Thanks again for your help,
Jc

**Comment by svenevs** [comment]
For those following along: ref #82 

Thanks Henry :slightly_smiling_face:

**Comment by jcfr** [comment]
Closing. See #82
