### ISSUE TITLE
Release new version on PyPI

### ISSUE THREAD

**Issue by henryiii** [scikit-build/cmake-python-distributions#83]
The source now has Cmake 3.15, but it has not been released on PyPI yet.

**Comment by jcfr** [comment]
oops, you are right. I didn't follow the release guide .. https://cmake-python-distributions.readthedocs.io/en/latest/make_a_release.html#pypi-step-by-step

I will create the tag now

**Comment by henryiii** [comment]
Update here when you do! Thanks.

**Comment by jcfr** [comment]
Tag has been pushed, release packages are being built. They should be available in the next hour or so.

**Comment by jcfr** [comment]
See https://github.com/scikit-build/cmake-python-distributions/releases/tag/3.15.2

**Comment by henryiii** [comment]
Thank you! By the way, is this 3.15.2 or 3.15.3? I started with 3.15.2 in my PR, but updated it to 3.15.3 since it was sitting there for a while. It looks like the tag is 3.15.2, though.

**Comment by jcfr** [comment]
Good catch. I will push an other tag and remove the 3.15.2 PyPI release.
