### ISSUE TITLE
Missing py3 wheel for macOS

### ISSUE THREAD

**Issue by papr** [scikit-build/cmake-python-distributions#84]
https://pypi.org/project/cmake/3.14.4/
- `cmake-3.14.4-py2-none-macosx_10_6_x86_64.whl` exists
- `cmake-3.14.4-py3-none-macosx_10_6_x86_64.whl` exists

https://pypi.org/project/cmake/3.15.2/#files
- `cmake-3.15.2-py2-none-macosx_10_6_x86_64.whl` exists
- `cmake-3.15.2-py3-none-macosx_10_6_x86_64.whl` **does not** exists

**Comment by jcfr** [comment]
Thanks for the report.

macOS python 3 wheel failed with the message copied below. I am looking into it now.


From https://travis-ci.org/scikit-build/cmake-python-distributions/jobs/588580844 : 
```
WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.

Could not fetch URL https://pypi.org/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pip/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping

Could not fetch URL https://github.com/[secure]/pytest-plugins/releases/tag/v1.7.0.dev15: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='github.com', port=443): Max retries exceeded with url: /[secure]/pytest-plugins/releases/tag/v1.7.0.dev15 (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping
```

**Comment by jcfr** [comment]
Issue is fixed by #85, will tag the 3.15.3 release shortly.  It turns out 3.15.2 was tagged by mistake 

Cc: @henryiii

**Comment by jcfr** [comment]
Pip installable release of CMake 3.15.3 is expected to be available shortly. See https://github.com/scikit-build/cmake-python-distributions/releases/tag/3.15.3

Cc: @Croydon  @henryiii

**Comment by papr** [comment]
Great, thank you for looking into the issue so quickly!

**Comment by jcfr** [comment]
You are welcome, linux packages are already available ... https://pypi.org/project/cmake/3.15.3/#files

Packages for the other systems will be available on workers become available for TravisCI (macOS) and Appveyor (windows):
* macOS: https://travis-ci.org/scikit-build/cmake-python-distributions/builds/589110229
* windows: https://ci.appveyor.com/project/scikit-build/cmake-python-distributions-f3rbb/builds/27638553

**Comment by Croydon** [comment]
macOS + Python 3 failed on Travis

**Comment by jcfr** [comment]
Hummm ... this is strange.

On master, I get:

![image](https://user-images.githubusercontent.com/219043/65547793-29687000-dee8-11e9-934a-20c3e247af50.png)


whereas for the build associated with the tag, I get:

![image](https://user-images.githubusercontent.com/219043/65548234-10ac8a00-dee9-11e9-84a8-00d4eeb89d69.png)

I wonder if the fact it is using a cached python install causing problem

**Comment by jcfr** [comment]
After clearing the cache, it worked. the package for macOS is now available.

**Comment by jcfr** [comment]
For now, I am closing the issue.
