### ISSUE TITLE
Install: ModuleNotFoundError: No module named 'skbuild'

### ISSUE THREAD

**Issue by Croydon** [scikit-build/cmake-python-distributions#86]
We have the following problem when trying to install 3.15.2:

```
pip install cmake --upgrade
Collecting cmake
  Downloading https://files.pythonhosted.org/packages/59/20/d1c7e0df29789e7c3aaef17d9952ed477d197cdb4e72d5e23beaf7f3e0c4/cmake-3.15.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/17/5mc7816d3mndxjqgplq6057w0000gn/T/pip-install-yng873yt/cmake/setup.py", line 7, in <module>
        from skbuild import setup
    ModuleNotFoundError: No module named 'skbuild'
```

We did not have such a problem with earlier versions.
Installing `scikit-build` via pip before installing `cmake` seems to fix this issue.

It's likely just missed in the dependency list of CMake?

// @ericLemanissier

**Comment by jcfr** [comment]
I am assuming this is on macos ? If yes, this will be fixed shortly. See #84

**Comment by Croydon** [comment]
Yes, it is on macOS.

Thanks!

**Comment by JesseFarebro** [comment]
I'm actually noticing the same issue on Linux as well, more specifically the PyPa manylinux1 docker container.

**Comment by jcfr** [comment]
Could you try again now ? 

I just removed the source distribution from pypi, this should allow pip to automatically find the last CMake version compatible with manylinux1. (instead of trying to build from source the most recent one). 

Indeed, we are now building recent CMake wheels on manylinux2010.

For reference, see https://github.com/pypa/pip/issues/6547 and https://github.com/pypa/pip/issues/6550

**Comment by JesseFarebro** [comment]
@jcfr still not working sadly:

```
+ sh -c 'pip install cmake==3.15.3'
Collecting cmake==3.15.3
  Downloading https://files.pythonhosted.org/packages/2c/9f/b3097fdeb7d09bb03255215245b32b48edf0d95e966f763407881d4b906a/cmake-3.15.3.tar.gz
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-yvve2iv3/cmake/setup.py", line 7, in <module>
        from skbuild import setup
    ImportError: No module named 'skbuild'
    ----------------------------------------
```

**Comment by jcfr** [comment]
For some reason, I didn't execute on what I wrote. The source archive has now been removed and it should not fail.

Thanks for your patience

**Comment by JesseFarebro** [comment]
Hey @jcfr, thanks for taking a look at this. The problem is solved I guess but it's installing the `3.13.X` version instead of `3.15.X`. I didn't specifically need `3.15.X` but I just thought I'd let you know.

**Comment by jcfr** [comment]
Thanks for the note.

Since the recent CMake wheels are not built with manylinux1 but with manylinux2010, this is expected ... 

Let me know if you would like more details.

**Comment by JesseFarebro** [comment]
Ahh makes sense. Thanks!

**Comment by chankim** [comment]
on CentOS8.2, just do "sudo pip3 install scikit-build".

**Comment by habibmuhammadthariq** [comment]
> on CentOS8.2, just do "sudo pip3 install scikit-build".

This worked for me in ubuntu 18.04. But FYI, i got another error after that.
