### ISSUE TITLE
Build manylinux1 wheel for Python 3.8 and cmake 3.13.2

### ISSUE THREAD

**Issue by filipArena** [scikit-build/cmake-python-distributions#89]
cmake 3.12.2 is the last version offering `manylinux1` due to new versions requiring 2010 `libuv` support. So when scikit-build uses cmake to build `manylinux1` wheels, it uses this version.

However, now that Python 3.8 is available, you cannot use scikit-build for `manylinux1` because there is no 3.8 `manylinux1` wheel for cmake. This **needs to be fixed** by having `cmake-3.12.2-cp38-manylinux1.whl`.

**Comment by filipArena** [comment]
I checked out to 3.13.2 and did  `docker run --rm -v $(pwd):/work dockcross/manylinux1-x86 /bin/bash -c 'PATH="/opt/python/cp38-cp38/bin:$PATH" && export CIRCLECI=True && pip install scikit-ci && ci'` and I built [cmake-3.13.2-cp38-cp38-manylinux1_i686.whl](https://drive.google.com/file/d/1Pt_IyOoHb5Rtk7vONKZEMEX-TgqpozJh/view?usp=sharing).

@jcfr Can we get it on PyPI?

**Comment by henryiii** [comment]
Can I second this? This breaks manylinux1 builds that require CMake in their pyproject.toml, and I'm having to work around it.

**Comment by thewtex** [comment]
[cmake-3.13.2.post1-cp38-cp38-manylinux1_x86_64.whl](https://files.pythonhosted.org/packages/9e/1d/1bed82c896d7bc0cfde828ecb0fdd82711fdbdcfbadaffef34b78e2fdf58/cmake-3.13.2.post1-cp38-cp38-manylinux1_x86_64.whl) built and uploaded! (note 3.13.2.post1 versus 3.13.2).

@filipArena I tried the same for the i686 arch, but encountered:

```
build/temp.linux-i686-3.8/_openssl.c:546:30: fatal error: openssl/opensslv.h: No such file or directory
 #include <openssl/opensslv.h>
```

Did you not encounter the same?

**Comment by filipArena** [comment]
@thewtex I did not have that issue but I don't have a dev environment at this moment. Will post an i368 update when I can.

**Comment by jcfr** [comment]
CircleCI now reports the error that @thewtex discussed in https://github.com/scikit-build/cmake-python-distributions/issues/89#issuecomment-595988747

See https://app.circleci.com/pipelines/github/scikit-build/cmake-python-distributions/20/workflows/f9337bba-56b0-4657-95ed-3235b35cca0b/jobs/2387/parallel-runs/0/steps/0-102

I will investigate further and report back.
