### ISSUE TITLE
manylinux2010_i686 wheels

### ISSUE THREAD

**Issue by Erotemic** [scikit-build/cmake-python-distributions#92]
I notice that the manylinux cmake wheels on pypi are only build for x64_64 architectures. Is there any chance we could also get i686 wheels as well?

I'm currently trying to `pip install cmake` on the manylinux2010_i686 docker image, but because there are no wheels explicitly built for it it tries to install the source wheel. However, to build the source wheel it requires a newer version of cmake than the version provided by centos.

**Comment by dotfloat** [comment]
As an alternative, you can install CMake 3.6.1 with `yum install cmake3` and then do
`python setup.py build --cmake-executable=/usr/bin/cmake3`.

**Comment by YannickJadoul** [comment]
Is anything stopping the project from adding these `manylinux2010_i686`-compatible wheels?
I'm happy to contribute, if necessary. Is there anything I can do?

**Comment by jcfr** [comment]
When we first enabled the build using manylinux2010, the x86 docker image was not available (see https://github.com/scikit-build/cmake-python-distributions/commit/cbf4565d440a4f3aa96f5c0b6cb3070aa9e8e949#diff-1d37e48f9ceff6d8030570cd36286a61v)

x86 image are now available, this will be addressed shortly.

**Comment by YannickJadoul** [comment]
Thanks a lot, @jcfr!
Will there soon be a new release, or will you still upload the wheels from the release to PyPI as well?

**Comment by jcfr** [comment]
Both

> or will you still upload the wheels from the release to PyPI as well?

First, following new wheels will be uploaded, these will be compatible with manylinux1:
* `3.14.3.post1`
* `3.14.4.post1`
* `3.15.3.post1`
* `3.16.3.post1`

> Will there soon be a new release, 

Then, wheels for `3.16.5` and `3.17.0` will also be uploaded.

I anticipate this to happen over the next few days

**Comment by YannickJadoul** [comment]
Amazing! Thanks :-)

**Comment by jcfr** [comment]
Et voila. Wheels for `3.14.3`, `3.14.4`, `3.15.3`, `3.16.3` are being built and should be automatically published in few hours.

**Comment by YannickJadoul** [comment]
Thanks! :-)
