### ISSUE TITLE
Documentation and Readme say that the python wheels provide 3.16, but only 3.15 is available

### ISSUE THREAD

**Issue by slurps-mad-rips** [scikit-build/cmake-python-distributions#93]
Hi! I think something might have been missed. It looks like the 3.16 release never occurred? PyPI says the last release was CMake 3.15.3 in September of 2019, which disagrees with what the readme currently states.

**Comment by henryiii** [comment]
I am trying out unity builds, and the lack of 3.16 on PyPI is getting in the way. Second the 3.16 release, please!

**Comment by jcfr** [comment]
Closing.

Thanks to @henryiii 3.16 wheels are now available (for reference https://github.com/scikit-build/cmake-python-distributions/pull/94)

As a side note, shortly I will re-generate wheel compatible with manylinux1 (see https://github.com/scikit-build/cmake-python-distributions/pull/97)
